name: PowerShell CI

on: [push, pull_request]

jobs:
  test:
    name: Lint and Test PowerShell Scripts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PowerShell
        uses: PowerShell/PowerShell@v1.2.0
        with:
          version: '7.4.x'

      - name: Run PSScriptAnalyzer
        run: |
          Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser
          Invoke-ScriptAnalyzer -Path . -Recurse
        shell: pwsh
